[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#1E1E1E"
secondaryBackgroundColor = "#313131"
textColor = "#FAFAFA"
font = "monospace"
base="auto" 
page_title = "easyFinance - by @MickyBi" 


[client]
toolbarMode = "minimal"  # Nasconde la barra degli strumenti
showErrorDetails = false  # Evita di mostrare errori dettagliati agli utenti
page_title = "easyFinance - by @MickyBi" 

[server]
runOnSave = true
page_title = "easyFinance - by @MickyBi" 

[caching]
enable = true 
